### PR TITLE
Added policy to vendor commands

### PR DESCRIPTION
**Pull request by ruabmbua**
wiphy_register() in the linux kernel checks for this, and fails when policy not set.

### CODE REVIEW

**Comment by kalekseev** [comment]
@EntropicEffect @ruabmbua this patch breaks build on ubuntu 18.04

```
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1403:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1403:13: error: ‘VENDOR_CMD_RAW_DATA’ undeclared here (not in a function); did you mean ‘VENDOR_CMD_MAX_DATA_LEN’?
   .policy = VENDOR_CMD_RAW_DATA,
             ^~~~~~~~~~~~~~~~~~~
             VENDOR_CMD_MAX_DATA_LEN
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1412:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1421:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1431:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/tmp/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1440:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
```

Similar issue in rtl8812au repo https://github.com/aircrack-ng/rtl8812au/issues/383#issuecomment-529192310

**Comment by ruabmbua** [comment]
@kalekseev What is your kernel version? (execute uname -a)

**Comment by ruabmbua** [comment]
This driver works on latest kernel for me (v5.3.1).

**Comment by JerryBlack** [comment]
On my new Odroid-N2,
odroid@odroid:~$ uname -r
4.9.190-62      (the most uptodate release for it -  Ubuntu Mate)
It fails, unless I comment out the .policy lines.

**Comment by kalekseev** [comment]
> This driver works on latest kernel for me (v5.3.1).

Original release of ubuntu 18.04 was on 4.15 kernel, 18.04.2 runs on 4.18 and only 18.04.3 runs on 5.0 kernel, considering that 18.04 is lts release I would add some ifdefs around your policy feature to support it for some time.

My case was I installed 18.04 and needed to upgrade it but couldn't connect to network because I couldn't compile the driver for wifi.

**Comment by cyantools** [comment]
The problem is still not solved on kernel 4.19.75-v7l+
It seems VENDOR_CMD_RAW_DATA is not defined anywhere

` CC [M]  /home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.o
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1403:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1403:13: error: ‘VENDOR_CMD_RAW_DATA’ undeclared here (not in a function); did you mean ‘VENDOR_CMD_MAX_DATA_LEN’?
   .policy = VENDOR_CMD_RAW_DATA,
             ^~~~~~~~~~~~~~~~~~~
             VENDOR_CMD_MAX_DATA_LEN
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1412:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1421:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1431:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
/home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.c:1440:4: error: ‘const struct wiphy_vendor_command’ has no member named ‘policy’
   .policy = VENDOR_CMD_RAW_DATA,
    ^~~~~~
make[2]: *** [scripts/Makefile.build:304: /home/pi/test/rtl8822bu/os_dep/linux/rtw_cfgvendor.o] Error 1
make[1]: *** [Makefile:1519: _module_/home/pi/test/rtl8822bu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.75-v7l+'
make: *** [Makefile:2001: modules] Error 2
`

**Comment by cyantools** [comment]
Solved it. I guess, just deleted all the ocurrences of `.policy = VENDOR_CMD_RAW_DATA,` and bam! works like a charm.
I have no idea if it will brake somewere else but at less I can now compile the driver and insall it.
Tested on kernel 4.19.75-v7l+
Monitor mode also working.
